#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "pico/stdlib.h"
#include "hardware/spi.h"
#include "hardware/gpio.h"
#include "display.h"

// =============================================================================
// TILE SPRITES ==> https://www.spriters-resource.com/arcade/pacman/asset/73389/
// =============================================================================

const uint16_t tile_0[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_1[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE
};

const uint16_t tile_2[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_3[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE
};

const uint16_t tile_4[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_5[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_6[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE
};

const uint16_t tile_7[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
};

const uint16_t tile_8[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_9[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE
};

const uint16_t tile_10[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_11[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_12[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_13[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_14[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_15[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_16[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_17[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_18[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_19[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK
};

const uint16_t tile_20[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_21[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_22[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_23[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_24[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK
};

const uint16_t tile_25[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_26[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
};

const uint16_t tile_27[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_28[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_29[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_30[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
};

const uint16_t tile_31[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_32[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_33[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_34[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_35[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_36[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
};

const uint16_t tile_37[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_38[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_39[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_40[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK
};

const uint16_t tile_41[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_42[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_43[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_44[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
};

// EMPTY TILE ===>
const uint16_t tile_45[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// PELLET TILE ===>
const uint16_t tile_46[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// POWER TILE ===> 
const uint16_t tile_47[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK,
BLACK, BLACK, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
};

// FACING LEFT ===>
const uint16_t face_left_tl[(TILE_WIDTH - 1) * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t face_left_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
};

const uint16_t face_left_bl[(TILE_WIDTH - 1) * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW,
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t face_left_br[TILE_WIDTH * TILE_HEIGHT] = {
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// FACING RIGHT ===>
const uint16_t face_right_tl[TILE_WIDTH * TILE_HEIGHT] = {
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
};

const uint16_t face_right_tr[(TILE_WIDTH - 1) * TILE_HEIGHT] = {
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
    YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t face_right_bl[TILE_WIDTH * TILE_HEIGHT] = {
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t face_right_br[(TILE_WIDTH - 1) * TILE_HEIGHT] = {
    YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
    YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// FACING UP ===>
const uint16_t face_up_tl[TILE_WIDTH * TILE_HEIGHT] = {
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
    BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
};

const uint16_t face_up_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
};

const uint16_t face_up_bl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t face_up_br[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// FACING DOWN ===>
const uint16_t face_down_tl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
};

const uint16_t face_down_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK
};

const uint16_t face_down_bl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
BLACK, BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK,
BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t face_down_br[TILE_WIDTH * TILE_HEIGHT] = {
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// RED GHOST ==>
const uint16_t red_tl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED,
BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED,
BLACK, BLACK, BLACK, RED, RED, RED, RED, RED,
BLACK, BLACK, RED, RED, RED, WHITE, WHITE, RED,
BLACK, BLACK, RED, RED, WHITE, WHITE, WHITE, WHITE,
BLACK, BLACK, RED, RED, WHITE, WHITE, BLUE, BLUE,
BLACK, RED, RED, RED, WHITE, WHITE, BLUE, BLUE,
};

const uint16_t red_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK,
RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK,
RED, RED, RED, WHITE, WHITE, RED, BLACK, BLACK,
RED, RED, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
RED, RED, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK,
RED, RED, WHITE, WHITE, BLUE, BLUE, BLACK, RED,
};

const uint16_t red_bl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, RED, RED, RED, RED, WHITE, WHITE, RED,
BLACK, RED, RED, RED, RED, RED, RED, RED,
BLACK, RED, RED, RED, RED, RED, RED, RED,
BLACK, RED, RED, RED, RED, RED, RED, RED,
BLACK, RED, RED, RED, RED, RED, RED, RED,
BLACK, RED, RED, BLACK, RED, RED, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, RED, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t red_br[TILE_WIDTH * TILE_HEIGHT] = {
RED, RED, RED, WHITE, WHITE, RED, RED, BLACK,
RED, RED, RED, RED, RED, RED, RED, BLACK,
RED, RED, RED, RED, RED, RED, RED, BLACK,
RED, RED, RED, RED, RED, RED, RED, BLACK,
RED, RED, RED, RED, RED, RED, RED, BLACK,
BLACK, RED, RED, RED, BLACK, RED, RED, BLACK,
BLACK, RED, RED, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t pink_tl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, PINK, PINK,
BLACK, BLACK, BLACK, BLACK, PINK, PINK, PINK, PINK,
BLACK, BLACK, BLACK, PINK, PINK, PINK, PINK, PINK,
BLACK, BLACK, PINK, PINK, PINK, WHITE, WHITE, PINK,
BLACK, BLACK, PINK, PINK, WHITE, WHITE, WHITE, WHITE,
BLACK, BLACK, PINK, PINK, WHITE, WHITE, BLUE, BLUE,
BLACK, PINK, PINK, PINK, WHITE, WHITE, BLUE, BLUE,
};

const uint16_t pink_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
PINK, PINK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
PINK, PINK, PINK, PINK, BLACK, BLACK, BLACK, BLACK,
PINK, PINK, PINK, PINK, PINK, BLACK, BLACK, BLACK, BLACK,
PINK, PINK, PINK, WHITE, WHITE, PINK, BLACK, BLACK,
PINK, PINK, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
PINK, PINK, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK,
PINK, PINK, WHITE, WHITE, BLUE, BLUE, BLACK, PINK,
};

const uint16_t pink_bl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, PINK, PINK, PINK, PINK, WHITE, WHITE, PINK,
BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK,
BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK,
BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK,
BLACK, PINK, PINK, PINK, PINK, PINK, PINK, PINK,
BLACK, PINK, PINK, BLACK, PINK, PINK, PINK, BLACK,
BLACK, PINK, BLACK, BLACK, BLACK, PINK, PINK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t pink_br[TILE_WIDTH * TILE_HEIGHT] = {
PINK, PINK, PINK, WHITE, WHITE, PINK, PINK, BLACK,
PINK, PINK, PINK, PINK, PINK, PINK, PINK, BLACK,
PINK, PINK, PINK, PINK, PINK, PINK, PINK, BLACK,
PINK, PINK, PINK, PINK, PINK, PINK, PINK, BLACK,
PINK, PINK, PINK, PINK, PINK, PINK, PINK, BLACK,
BLACK, PINK, PINK, PINK, BLACK, PINK, PINK, BLACK,
BLACK, PINK, PINK, BLACK, BLACK, BLACK, PINK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// ORANGE GHOST ==>
const uint16_t orange_tl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE, ORANGE,
BLACK, BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE,
BLACK, BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
BLACK, BLACK, ORANGE, ORANGE, ORANGE, WHITE, WHITE, ORANGE,
BLACK, BLACK, ORANGE, ORANGE, WHITE, WHITE, WHITE, WHITE,
BLACK, BLACK, ORANGE, ORANGE, WHITE, WHITE, BLUE, BLUE,
BLACK, ORANGE, ORANGE, ORANGE, WHITE, WHITE, BLUE, BLUE,
};

const uint16_t orange_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK, BLACK,
ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK,
ORANGE, ORANGE, ORANGE, WHITE, WHITE, ORANGE, BLACK, BLACK,
ORANGE, ORANGE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
ORANGE, ORANGE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK,
ORANGE, ORANGE, WHITE, WHITE, BLUE, BLUE, BLACK, ORANGE,
};

const uint16_t orange_bl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, WHITE, WHITE, ORANGE,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
BLACK, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t orange_br[TILE_WIDTH * TILE_HEIGHT] = {
ORANGE, ORANGE, ORANGE, WHITE, WHITE, ORANGE, ORANGE, BLACK,
ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, ORANGE, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// BLUE GHOST ==>
const uint16_t blue_tl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, LIGHTBLUE, LIGHTBLUE,
BLACK, BLACK, BLACK, BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE,
BLACK, BLACK, BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE,
BLACK, BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, LIGHTBLUE,
BLACK, BLACK, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, WHITE, WHITE,
BLACK, BLACK, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, BLUE, BLUE,
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, BLUE, BLUE,
};

const uint16_t blue_tr[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK, BLACK, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, LIGHTBLUE, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, BLUE, BLUE, BLACK, BLACK,
LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, BLUE, BLUE, BLACK, LIGHTBLUE,
};

const uint16_t blue_bl[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, LIGHTBLUE,
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE,
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE,
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE,
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE,
BLACK, LIGHTBLUE, LIGHTBLUE, BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK,
BLACK, LIGHTBLUE, BLACK, BLACK, BLACK, LIGHTBLUE, LIGHTBLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t blue_br[TILE_WIDTH * TILE_HEIGHT] = {
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, WHITE, WHITE, LIGHTBLUE, LIGHTBLUE, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK,
LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK,
BLACK, LIGHTBLUE, LIGHTBLUE, LIGHTBLUE, BLACK, LIGHTBLUE, LIGHTBLUE, BLACK,
BLACK, LIGHTBLUE, LIGHTBLUE, BLACK, BLACK, BLACK, LIGHTBLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// EATABLE GHOST ===>
// Quadrant: Top Left (tl)
const uint16_t eatable_tl[TILE_WIDTH * TILE_HEIGHT] = {
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,  BLUE,
    BLACK, BLACK, BLACK, BLACK, BLUE,  BLUE,  BLUE,  BLUE,
    BLACK, BLACK, BLACK, BLUE,  BLUE,  BLUE,  BLUE,  BLUE,
    BLACK, BLACK, BLUE,  BLUE,  BLUE,  WHITE, WHITE, BLUE,
    BLACK, BLACK, BLUE,  BLUE,  WHITE, WHITE, WHITE, WHITE,
    BLACK, BLACK, BLUE,  BLUE,  WHITE, WHITE, PINK,  PINK,
    BLACK, BLUE,  BLUE,  BLUE,  WHITE, WHITE, PINK,  PINK,
};

// Quadrant: Top Right (tr)
const uint16_t eatable_tr[TILE_WIDTH * TILE_HEIGHT] = {
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLUE,  BLUE,  BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLUE,  BLUE,  BLUE,  BLUE,  BLACK, BLACK, BLACK, BLACK,
    BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLACK, BLACK, BLACK,
    BLUE,  BLUE,  BLUE,  WHITE, WHITE, BLUE,  BLACK, BLACK,
    BLUE,  BLUE,  WHITE, WHITE, WHITE, WHITE, BLACK, BLACK,
    BLUE,  BLUE,  WHITE, WHITE, PINK,  PINK,  BLACK, BLACK,
    BLUE,  BLUE,  WHITE, WHITE, PINK,  PINK,  BLACK, BLUE,
};

// Quadrant: Bottom Left (bl)
const uint16_t eatable_bl[TILE_WIDTH * TILE_HEIGHT] = {
    BLACK, BLUE,  BLUE,  BLUE,  BLUE,  WHITE, WHITE, BLUE,
    BLACK, BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,
    BLACK, BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,
    BLACK, BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,
    BLACK, BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,
    BLACK, BLUE,  BLUE,  BLACK, BLUE,  BLUE,  BLUE,  BLACK,
    BLACK, BLUE,  BLACK, BLACK, BLACK, BLUE,  BLUE,  BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// Quadrant: Bottom Right (br)
const uint16_t eatable_br[TILE_WIDTH * TILE_HEIGHT] = {
    BLUE,  BLUE,  BLUE,  WHITE, WHITE, BLUE,  BLUE,  BLACK,
    BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLACK,
    BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLACK,
    BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLACK,
    BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLACK,
    BLACK, BLUE,  BLUE,  BLUE,  BLACK, BLUE,  BLUE,  BLACK,
    BLACK, BLUE,  BLUE,  BLACK, BLACK, BLACK, BLUE,  BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// LETTERS / NUMBERS ==> https://www.freepik.com/free-vector/flat-design-digital-display-font_44130967.htm#fromView=keyword&page=1&position=2&uuid=eb967466-5b54-40eb-a973-8917ecb664af&query=Pixel+art+alphabet
const uint16_t letter_p[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_r[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t red_letter_r[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, RED, RED, RED, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, RED, RED, RED, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_e[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t red_letter_e[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, RED, RED, RED, RED, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, RED, RED, RED, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, RED, RED, RED, RED, RED, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_s[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_te[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_a[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t red_letter_a[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, RED, RED, RED, RED, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_d[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK,
BLACK, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_g[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, RED, RED, RED, RED, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, BLACK, RED, RED, RED, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_m[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, RED, BLACK, RED, RED, BLACK, BLACK,
BLACK, RED, BLACK, RED, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_o[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, RED, RED, RED, BLACK, BLACK,
BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK,
BLACK, BLACK, BLACK, RED, RED, RED, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_u[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, ORANGE, BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK,
BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_v[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, RED, BLACK, BLACK, BLACK, RED, BLACK, BLACK,
BLACK, BLACK, RED, BLACK, RED, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t letter_exclam[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, ORANGE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t red_letter_exclam[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, RED, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// ==========================================================================
//                              DEFAULT MAP
// ==========================================================================

const uint8_t initial_tile_map[NUM_TILES_Y][NUM_TILES_X] = {
    {2, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 44, 43, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 1,},
    {4, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 3,},
    {4, 46, 40, 16, 16, 39, 46, 40, 16, 16, 16, 39, 46, 26, 25, 46, 40, 16, 16, 16, 39, 46, 40, 16, 16, 39, 46, 3,}, 
    {4, 47, 26, 45, 45, 25, 46, 26, 45, 45, 45, 25, 46, 26, 25, 46, 26, 45, 45, 45, 25, 46, 26, 45, 45, 25, 47, 3,},
    {4, 46, 28, 21, 21, 27, 46, 28, 21, 21, 21, 27, 46, 28, 27, 46, 28, 21, 21, 21, 27, 46, 28, 21, 21, 27, 46, 3,},
    {4, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 3,},
    {4, 46, 40, 16, 16, 39, 46, 40, 39, 46, 40, 16, 16, 16, 16, 16, 16, 39, 46, 40, 39, 46, 40, 16, 16, 39, 46, 3,},
    {4, 46, 42, 21, 21, 41, 46, 26, 25, 46, 42, 21, 21, 36, 35, 21, 21, 41, 46, 26, 25, 46, 42, 21, 21, 41, 46, 3,},
    {4, 46, 46, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 46, 46, 3,},
    {6, 14, 14, 14, 14, 39, 46, 26, 37, 16, 16, 39, 45, 26, 25, 45, 24, 16, 16, 38, 25, 46, 40, 14, 14, 14, 14, 5,},
    {45, 45, 45, 45, 45, 4, 46, 26, 35, 21, 21, 27, 45, 42, 41, 45, 42, 21, 21, 36, 25, 46, 3, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 4, 46, 26, 25, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 26, 25, 46, 3, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 4, 46, 26, 25, 45, 30, 14, 34, 0, 0, 33, 14, 29, 45, 26, 25, 46, 3, 45, 45, 45, 45, 45,},
    {12, 12, 12, 12, 12, 27, 46, 42, 41, 45, 3, 45, 45, 45, 45, 45, 45, 4, 45, 42, 41, 46, 28, 12, 12, 12, 12, 12,},
    {45, 45, 45, 45, 45, 45, 46, 45, 45, 45, 3, 45, 45, 45, 45, 45, 45, 4, 45, 45, 45, 46, 45, 45, 45, 45, 45, 45,},
    {14, 14, 14, 14, 14, 39, 46, 40, 39, 45, 3, 45, 45, 45, 45, 45, 45, 4, 45, 40, 39, 46, 24, 14, 14, 14, 14, 14,},
    {45, 45, 45, 45, 45, 4, 46, 26, 25, 45, 32, 12, 12, 12, 12, 12, 12, 31, 45, 26, 25, 46, 3, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 4, 46, 26, 25, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 26, 25, 46, 3, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 4, 46, 26, 25, 45, 40, 16, 16, 16, 16, 16, 16, 39, 45, 26, 25, 46, 3, 45, 45, 45, 45, 45,},
    {2, 12, 12, 12, 12, 27, 46, 28, 27, 46, 28, 21, 21, 36, 35, 21, 21, 27, 46, 28, 27, 46, 28, 12, 12, 12, 12, 1,},
    {4, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 3,},
    {4, 46, 24, 16, 16, 23, 46, 24, 16, 16, 16, 23, 46, 26, 25, 46, 24, 16, 16, 16, 23, 46, 24, 16, 16, 23, 46, 3,}, 
    {4, 46, 28, 21, 36, 25, 46, 28, 21, 21, 21, 27, 46, 28, 27, 46, 28, 21, 21, 21, 27, 46, 26, 35, 21, 27, 46, 3,},
    {4, 47, 46, 46, 26, 25, 46, 46, 46, 46, 45, 45, 45, 45, 45, 45, 45, 46, 46, 46, 46, 46, 26, 25, 46, 46, 47, 3,},
    {8, 16, 39, 46, 26, 25, 46, 40, 39, 46, 40, 16, 16, 16, 16, 16, 16, 39, 46, 40, 39, 46, 26, 25, 46, 40, 16, 7,},
    {10, 21, 27, 46, 28, 27, 46, 26, 25, 46, 28, 21, 21, 36, 35, 21, 21, 27, 46, 26, 25, 46, 28, 27, 46, 28, 21, 9,},
    {4, 46, 46, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 26, 25, 46, 46, 46, 46, 46, 46, 3,},
    {4, 46, 40, 16, 16, 16, 16, 38, 37, 16, 16, 39, 46, 26, 25, 46, 40, 16, 16, 38, 37, 16, 16, 16, 16, 39, 46, 3,},
    {4, 46, 28, 21, 21, 21, 21, 21, 21, 21, 21, 27, 46, 28, 27, 46, 28, 21, 21, 21, 21, 21, 21, 21, 21, 27, 46, 3,},
    {4, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 3,},
    {6, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 5,}
};

uint8_t tile_map[NUM_TILES_Y][NUM_TILES_X] = {0};

// 7-segment display buffer for score and lives
extern char font[];
uint16_t __attribute__((aligned(16))) ssd_msg_buffer[8] = {0};

// Pointers to all tiles for easy lookup
const uint16_t* const tile_ptrs[48] = {
    tile_0, tile_1, tile_2, tile_3, tile_4, tile_5, tile_6, tile_7, tile_8, tile_9,
    tile_10, tile_11, tile_12, tile_13, tile_14, tile_15, tile_16, tile_17, tile_18, tile_19,
    tile_20, tile_21, tile_22, tile_23, tile_24, tile_25, tile_26, tile_27, tile_28, tile_29,
    tile_30, tile_31, tile_32, tile_33, tile_34, tile_35, tile_36, tile_37, tile_38, tile_39,
    tile_40, tile_41, tile_42, tile_43, tile_44, tile_45, tile_46, tile_47
};

void tft_write_command(uint8_t cmd){
    gpio_put(TFT_DC, 0); // Command mode
    gpio_put(TFT_SPI_CSN, 0);
    spi_write_blocking(spi0, &cmd, 1);
    gpio_put(TFT_SPI_CSN, 1);
}

void tft_write_data(uint8_t data){
    gpio_put(TFT_DC, 1); // Data mode
    gpio_put(TFT_SPI_CSN, 0);
    spi_write_blocking(spi0, &data, 1);
    gpio_put(TFT_SPI_CSN, 1);
}

void tft_set_address_window(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) {
    // Column Address Set
    tft_write_command(0x2A);
    tft_write_data(x0 >> 8);
    tft_write_data(x0 & 0xFF);
    tft_write_data(x1 >> 8);
    tft_write_data(x1 & 0xFF);

    // Row Address Set
    tft_write_command(0x2B);
    tft_write_data(y0 >> 8);
    tft_write_data(y0 & 0xFF);
    tft_write_data(y1 >> 8);
    tft_write_data(y1 & 0xFF);

    // Write to RAM
    tft_write_command(0x2C);
}

void ssd_init_spi() {
    // fill in 
    gpio_init(SSD_SPI_SCK);
    gpio_init(SSD_SPI_CSN);
    gpio_init(SSD_SPI_MOSI);
    
    gpio_set_function(SSD_SPI_SCK, GPIO_FUNC_SPI);
    gpio_set_function(SSD_SPI_CSN, GPIO_FUNC_SPI);
    gpio_set_function(SSD_SPI_MOSI, GPIO_FUNC_SPI);

    spi_init(spi1, 125000);
    spi_set_format(spi1, 16, 0, 0, SPI_MSB_FIRST);  
    
}

uint16_t __attribute__((aligned(16))) msg[8] = {
    (0 << 8) | 0x3F, // seven-segment value of 0
    (1 << 8) | 0x06, // seven-segment value of 1
    (2 << 8) | 0x5B, // seven-segment value of 2
    (3 << 8) | 0x4F, // seven-segment value of 3
    (4 << 8) | 0x66, // seven-segment value of 4
    (5 << 8) | 0x6D, // seven-segment value of 5
    (6 << 8) | 0x7D, // seven-segment value of 6
    (7 << 8) | 0x07, // seven-segment value of 7
};

void ssd_display_score(ScoreBoard scoreboard) {

    // font array for number mapping
    char font[] = {0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 0x7F, 0x67};

    uint8_t score_h = (scoreboard.score / 100) % 10;
    uint8_t score_t = (scoreboard.score / 10) % 10;
    uint8_t score_o = scoreboard.score % 10;

    msg[0] = (0 << 8) | font[score_h];
    msg[1] = (1 << 8) | font[score_t];
    msg[2] = (2 << 8) | font[score_o];

    for (int i = 3; i <= 6; i++) {
        msg[i] = (i << 8) | 0x00; 
    }

    uint8_t lives_digit = scoreboard.lives % 10;
    msg[7] = (7 << 8) | font[lives_digit];

    spi_write16_blocking(spi1, msg, 8);
}

bool ssd_timer_callback(struct repeating_timer *t) {
    gpio_put(SSD_SPI_CSN, 0);
    spi_write16_blocking(spi1, ssd_msg_buffer, 8);
    gpio_put(SSD_SPI_CSN, 1);
    
    return true;
}

void display_init(){
    
    // Initialize Pins and SPI
    gpio_init(TFT_SPI_SCK);
    gpio_init(TFT_SPI_MOSI);

    gpio_set_function(TFT_SPI_SCK, GPIO_FUNC_SPI);
    gpio_set_function(TFT_SPI_MOSI, GPIO_FUNC_SPI);

    gpio_init(TFT_SPI_CSN);
    gpio_init(TFT_DC);
    gpio_init(TFT_RST);

    gpio_set_dir(TFT_SPI_CSN, GPIO_OUT);
    gpio_set_dir(TFT_DC, GPIO_OUT);
    gpio_set_dir(TFT_RST, GPIO_OUT);

    spi_init(spi0, 16000000);

    // Reset Display
    gpio_put(TFT_RST, 0);
    sleep_ms(10);
    gpio_put(TFT_RST, 1);
    sleep_ms(10);

    // Basic Initialization Sequence
    tft_write_command(0x01); // Software Reset
    sleep_ms(100);
    tft_write_command(0x11); // Exit Sleep
    sleep_ms(100);

    // Set Pixel Format to 16-bit (RGB565)
    tft_write_command(0x3A);
    tft_write_data(0x55);
    sleep_ms(100);

    // Using Landscape mode. x goes to 319 and y goes to 239 (320x249)
    tft_write_command(0x36);
    tft_write_data(0x28);

    tft_write_command(0x29); // Display ON
}

void ssd_update_buffer(ScoreBoard scoreboard) {
    char display_string[9];
    snprintf(display_string, sizeof(display_string), "%05d  %1d", scoreboard.score, scoreboard.lives);
    for (int i = 0; i < 8; i++) {
        unsigned char c = display_string[i];
        uint16_t seg = font[c];
        ssd_msg_buffer[i] = (i << 8) | seg;
    }
}

static inline void tft_fill_region(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color) {
    uint32_t num_pixels = (uint32_t)(x1 - x0 + 1) * (y1 - y0 + 1);

    uint8_t hi = (uint8_t)(color >> 8);
    uint8_t lo = (uint8_t)(color & 0xFF);

    // Build fill buffer
    static uint8_t fill_buf[2 * TILE_WIDTH * TILE_HEIGHT * 4];
    uint32_t buf_pixels = num_pixels < (sizeof(fill_buf) / 2) ? num_pixels : (sizeof(fill_buf) / 2);
    for (uint32_t i = 0; i < buf_pixels; i++) {
        fill_buf[i * 2]     = hi;
        fill_buf[i * 2 + 1] = lo;
    }

    tft_set_address_window(x0, y0, x1, y1);
    gpio_put(TFT_DC, 1);
    gpio_put(TFT_SPI_CSN, 0);

    uint32_t pixels_sent = 0;
    while (pixels_sent < num_pixels) {
        uint32_t chunk = num_pixels - pixels_sent;
        if (chunk > buf_pixels) chunk = buf_pixels;
        spi_write_blocking(spi0, fill_buf, chunk * 2);
        pixels_sent += chunk;
    }

    gpio_put(TFT_SPI_CSN, 1);
}

void tft_fill_screen(uint16_t color) {
    tft_fill_region(0, 0, 319, 239, color);
}

void tft_write_tile(const uint16_t* tile, uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) {
    tft_set_address_window(x0, y0, x1, y1);
    gpio_put(TFT_DC, 1);
    gpio_put(TFT_SPI_CSN, 0);
    for (int i = 0; i < TILE_WIDTH * TILE_HEIGHT; i++) {
        uint8_t buf[2] = { (uint8_t)(tile[i] >> 8), (uint8_t)(tile[i] & 0xFF) };
        spi_write_blocking(spi0, buf, 2);
    }
    gpio_put(TFT_SPI_CSN, 1);
}

void tft_write_sliced_tile(const uint16_t* tile, uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) {
    tft_set_address_window(x0, y0, x1, y1);
    gpio_put(TFT_DC, 1);
    gpio_put(TFT_SPI_CSN, 0);
    for (int i = 0; i < (TILE_WIDTH - 1) * TILE_HEIGHT; i++) {
        uint8_t buf[2] = { (uint8_t)(tile[i] >> 8), (uint8_t)(tile[i] & 0xFF) };
        spi_write_blocking(spi0, buf, 2);
    }
    gpio_put(TFT_SPI_CSN, 1);
}

void draw_map(){
    for(int i = 0; i < NUM_TILES_Y; i ++){
        for(int j = 0; j < NUM_TILES_X; j ++){
            
            uint16_t x0 = j * TILE_WIDTH + HORIZONTAL_OFFSET;
            uint16_t y0 = i * TILE_HEIGHT;
            uint16_t x1 = x0 + TILE_WIDTH - 1;
            uint16_t y1 = y0 + TILE_HEIGHT - 1;

            uint8_t tile_sel = tile_map[i][j];

            tft_write_tile(tile_ptrs[tile_sel], x0, y0, x1, y1);
        }
    }
}

void reset_game_map() {
    memcpy(tile_map, initial_tile_map, sizeof(tile_map));
}

// Reset only the characters back to their starting positions and states
void reset_sprites(PacmanState* p, GhostState* g1, GhostState* g2) {
    // Reset pacman
    p->x = PACMAN_START_X;
    p->y = PACMAN_START_Y;
    p->lastx = PACMAN_START_X;
    p->lasty = PACMAN_START_Y;
    p->direction = FACING_RIGHT;
    p->mode = NORMAL;

    // Reset ghosts
    g1->x = HOUSE_START_LEFT_X;
    g1->y = HOUSE_START_LEFT_Y;
    g1->lastx = HOUSE_START_LEFT_X;
    g1->lasty = HOUSE_START_LEFT_Y;
    g1->location = IN_HOUSE;
    g1->direction = 3; // Reset direction to right
    
    g2->x = HOUSE_START_RIGHT_X;
    g2->y = HOUSE_START_RIGHT_Y;
    g2->lastx = HOUSE_START_RIGHT_X;
    g2->lasty = HOUSE_START_RIGHT_Y;
    g2->location = IN_HOUSE;
    g2->direction = 1; // Reset direction to left

    // Redraw map to clear old Pacman and Ghosts
    draw_map();
}

// Reset the entire level (map, scoreboard, and pacman + ghosts)
void reset_level(PacmanState* p, GhostState* g1, GhostState* g2, ScoreBoard* s) {
    
    // Reset map
    reset_game_map();

    // Reset scoreboard
    s->num_pellets = 237;
    s->num_powers = 4;
    s->total_food = 241;
    
    // Reset entities to default
    reset_sprites(p, g1, g2);
}

void update_pacman(InputState controls, PacmanState* pacman) {
    pacman->lastx = pacman->x;
    pacman->lasty = pacman->y;

    int next_x = pacman->x;
    int next_y = pacman->y;

    int input_x = pacman->x;
    int input_y = pacman->y;
    int input_dir = pacman->direction;

    // Default coordinates to move in direction pac-man is currently facing
    switch (pacman->direction) {
        case FACING_UP: next_y -= 1; break;
        case FACING_DOWN: next_y += 1; break;
        case FACING_LEFT: next_x -= 1; break;
        case FACING_RIGHT: next_x += 1; break;
    }

    // Wrap default coordinates if past tunnel bounds
    if (next_x < 0) next_x = 27;
    if (next_x > 27) next_x = 0;

    // Determine intended joystick input
    if (controls.joystick == INPUT_DIRECTION_UP) {
        input_y -= 1;
        input_dir = FACING_UP;
    } else if (controls.joystick == INPUT_DIRECTION_DOWN)  {
        input_y += 1;
        input_dir = FACING_DOWN;
    } else if (controls.joystick == INPUT_DIRECTION_LEFT)  {
        input_x -= 1;
        input_dir = FACING_LEFT;
    } else if (controls.joystick == INPUT_DIRECTION_RIGHT) {
        input_x += 1;
        input_dir = FACING_RIGHT;
    } else if (controls.joystick == INPUT_DIRECTION_NONE) {
        input_x = next_x;
        input_y = next_y;
    }

    // Wrap joystick coordinates if past tunnel bounds
    if (input_x < 0) input_x = 27;
    if (input_x > 27) input_x = 0;

    /* Try moving in joystick direction first. If joystick is going
       into a wall, then try direction pac-man is currently facing.
       If pac-man is facing a wall, do nothing */
    if (tile_map[input_y][input_x] >= 45) {
        pacman->x = input_x;
        pacman->y = input_y;
        pacman->direction = input_dir;
        return;
    } else if (tile_map[next_y][next_x] >= 45) {
        pacman->x = next_x;
        pacman->y = next_y;
        return;
    }
}

void draw_pacman(InputState controls, PacmanState pacman){
    uint8_t sel = 0;
    uint16_t x0;
    uint16_t y0;
    uint16_t x1;
    uint16_t y1;

    // Draw the pacman tiles
    for(int i = 0; i < NUM_PACMAN_TILES_Y; i ++){
        for(int j = 0; j < NUM_PACMAN_TILES_X; j ++){
            
            x0 = (pacman.x + j) * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
            y0 = (pacman.y + i) * TILE_HEIGHT - (TILE_HEIGHT / 2);
            x1 = x0 + TILE_WIDTH - 1;
            y1 = y0 + TILE_HEIGHT - 1;

            switch(sel){
                case 0: (pacman.direction == FACING_LEFT) ? tft_write_sliced_tile(face_left_tl, x0 + 1, y0, x1, y1) :
                        (pacman.direction == FACING_RIGHT) ? tft_write_tile(face_right_tl, x0, y0, x1, y1)          :
                        (pacman.direction == FACING_UP) ? tft_write_tile(face_up_tl, x0, y0, x1, y1)                :
                        (pacman.direction == FACING_DOWN) ? tft_write_tile(face_down_tl, x0, y0, x1, y1)            : (void)0;
                break;
                case 1: (pacman.direction == FACING_LEFT) ? tft_write_tile(face_left_tr, x0, y0, x1, y1)             :
                        (pacman.direction == FACING_RIGHT) ? tft_write_sliced_tile(face_right_tr, x0, y0, x1 - 1, y1):
                        (pacman.direction == FACING_UP) ? tft_write_tile(face_up_tr, x0, y0, x1, y1)                 :
                        (pacman.direction == FACING_DOWN) ? tft_write_tile(face_down_tr, x0, y0, x1, y1)             : (void)0;
                break;
                case 2: (pacman.direction == FACING_LEFT) ? tft_write_sliced_tile(face_left_bl, x0 + 1, y0, x1, y1) :
                        (pacman.direction == FACING_RIGHT) ? tft_write_tile(face_right_bl, x0, y0, x1, y1)          :
                        (pacman.direction == FACING_UP) ? tft_write_tile(face_up_bl, x0, y0, x1, y1)                :
                        (pacman.direction == FACING_DOWN) ? tft_write_tile(face_down_bl, x0, y0, x1, y1)            : (void)0;
                break; 
                case 3: (pacman.direction == FACING_LEFT) ? tft_write_tile(face_left_br, x0, y0, x1, y1)             :
                        (pacman.direction == FACING_RIGHT) ? tft_write_sliced_tile(face_right_br, x0, y0, x1 - 1, y1):
                        (pacman.direction == FACING_UP) ? tft_write_tile(face_up_br, x0, y0, x1, y1)                 :
                        (pacman.direction == FACING_DOWN) ? tft_write_tile(face_down_br, x0, y0, x1, y1)             : (void)0;
                break;
            }
            sel ++;
        }
    }

    // Redraw black to the direction he was coming from
    uint16_t fill_color = BLACK;

    // Redraw wrap around
    if (pacman.x != pacman.lastx || pacman.y != pacman.lasty) {
        x0 = pacman.lastx * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
        x1 = x0 + (2 * TILE_WIDTH) - 1;
        y0 = pacman.lasty * TILE_HEIGHT - (TILE_HEIGHT / 2);
        y1 = y0 + (2 * TILE_HEIGHT) - 1;

        // Crop the box based on direction
        if (pacman.lastx < pacman.x && !(pacman.lastx == 0 && pacman.x == 27)) {
        x1 -= TILE_WIDTH;   // Moving right: crop the right edge
        } 
        else if (pacman.lastx > pacman.x && !(pacman.lastx == 27 && pacman.x == 0)) {
            x0 += TILE_WIDTH;   // Moving left: crop the left edge
        } 
        else if (pacman.lasty < pacman.y) {
            y1 -= TILE_HEIGHT;  // Moving down: crop the bottom edge
        } 
        else if (pacman.lasty > pacman.y) {
            y0 += TILE_HEIGHT;  // Moving up: crop the top edge
        }
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }
}
void draw_letter(const uint16_t* tile, uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1){
    tft_write_tile(tile, x0, y0, x1, y1);
}

void draw_start_screen(){
    uint16_t x0 = 115;
    uint16_t y0 = 13 * TILE_HEIGHT;
    uint16_t x1 = x0 + TILE_WIDTH - 1;
    uint16_t y1 = y0 + TILE_HEIGHT - 1;

    draw_letter(letter_p, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_r, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_e, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_s, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_s, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(tile_45, x0, y0, x1, y1); // Space
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_s, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_te, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_a, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_r, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_te, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_exclam, x0, y0, x1, y1);
}

void draw_paused_screen(){
    uint16_t x0 = 136; 
    uint16_t y0 = 13 * TILE_HEIGHT;
    uint16_t x1 = x0 + TILE_WIDTH - 1;
    uint16_t y1 = y0 + TILE_HEIGHT - 1;

    draw_letter(letter_p, x0, y0, x1, y1);
    x0 += 8; x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_a, x0, y0, x1, y1);
    x0 += 8; x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_u, x0, y0, x1, y1);
    x0 += 8; x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_s, x0, y0, x1, y1);
    x0 += 8; x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_e, x0, y0, x1, y1);
    x0 += 8; x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_d, x0, y0, x1, y1);
}

void draw_ghost(GhostState ghost, PacmanState pacman){
    uint8_t sel = 0;
    uint16_t x0;
    uint16_t y0;
    uint16_t x1;
    uint16_t y1;

    for (int i = 0; i < NUM_GHOST_TILES_Y; i ++){
        for(int j = 0; j < NUM_GHOST_TILES_X; j ++){
            
            x0 = (ghost.x + j) * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
            y0 = (ghost.y + i) * TILE_HEIGHT - (TILE_HEIGHT / 2);
            x1 = x0 + TILE_WIDTH - 1;
            y1 = y0 + TILE_HEIGHT - 1;

            switch(sel){
                case(0): pacman.mode == CHOMPER ? tft_write_tile(eatable_tl, x0, y0, x1, y1) :
                         ghost.color == COLOR_RED ? tft_write_tile(red_tl, x0, y0, x1, y1) : 
                         ghost.color == COLOR_PINK ? tft_write_tile(pink_tl, x0, y0, x1, y1) :
                         ghost.color == COLOR_ORANGE ? tft_write_tile(orange_tl, x0, y0, x1, y1) : 
                         ghost.color == COLOR_BLUE ? tft_write_tile(blue_tl, x0, y0, x1, y1) : (void)0;
                break;
                case(1): pacman.mode == CHOMPER ? tft_write_tile(eatable_tr, x0, y0, x1, y1) :
                         ghost.color == COLOR_RED ? tft_write_tile(red_tr, x0, y0, x1, y1) :
                         ghost.color == COLOR_PINK ? tft_write_tile(pink_tr, x0, y0, x1, y1) :
                         ghost.color == COLOR_ORANGE ? tft_write_tile(orange_tr, x0, y0, x1, y1) : 
                         ghost.color == COLOR_BLUE ? tft_write_tile(blue_tr, x0, y0, x1, y1) : (void)0;
                break;
                case(2): pacman.mode == CHOMPER ? tft_write_tile(eatable_bl, x0, y0, x1, y1) :
                         ghost.color == COLOR_RED ? tft_write_tile(red_bl, x0, y0, x1, y1) :
                         ghost.color == COLOR_PINK ? tft_write_tile(pink_bl, x0, y0, x1, y1) :
                         ghost.color == COLOR_ORANGE ? tft_write_tile(orange_bl, x0, y0, x1, y1) : 
                         ghost.color == COLOR_BLUE ? tft_write_tile(blue_bl, x0, y0, x1, y1) : (void)0;
                break;
                case(3): pacman.mode == CHOMPER ? tft_write_tile(eatable_br, x0, y0, x1, y1) : 
                         ghost.color == COLOR_RED ? tft_write_tile(red_br, x0, y0, x1, y1) :
                         ghost.color == COLOR_PINK ? tft_write_tile(pink_br, x0, y0, x1, y1) :
                         ghost.color == COLOR_ORANGE ? tft_write_tile(orange_br, x0, y0, x1, y1) : 
                         ghost.color == COLOR_BLUE ? tft_write_tile(blue_br, x0, y0, x1, y1) : (void)0;
                break;
                default:
                break;
            }
            sel ++;
        }
    }

    // Redraw black the direction the ghost came from
    uint16_t fill_color = BLACK;

    if(ghost.lastx < ghost.x){
        x0 = ghost.lastx * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
        x1 = x0 + TILE_WIDTH - 1;
        y0 = ghost.lasty * TILE_HEIGHT - (TILE_HEIGHT / 2);
        y1 = y0 + (2 * TILE_HEIGHT - 1);
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }
    else if(ghost.lastx > ghost.x){
        x0 = ghost.lastx * TILE_WIDTH + HORIZONTAL_OFFSET + (TILE_WIDTH / 2);
        x1 = x0 + TILE_WIDTH - 1;
        y0 = ghost.lasty * TILE_HEIGHT - (TILE_HEIGHT / 2);
        y1 = y0 + (2 * TILE_HEIGHT - 1);
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }
    else if(ghost.lasty < ghost.y) {
        x0 = ghost.lastx * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
        x1 = x0 + (2 * TILE_WIDTH - 1);
        y0 = ghost.lasty * TILE_HEIGHT - (TILE_HEIGHT / 2);
        y1 = y0 + TILE_HEIGHT - 1;
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }   
    else if (ghost.lasty > ghost.y) {
        x0 = ghost.lastx * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
        x1 = x0 + (2 * TILE_WIDTH - 1);
        y0 = ghost.lasty * TILE_HEIGHT + (TILE_HEIGHT / 2);
        y1 = y0 + TILE_HEIGHT - 1;
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }

     // Write a pellet / power if it is there --> Makes the ghosts look a little weird but whatever
    if(tile_map[ghost.lasty][ghost.lastx] == 46 || tile_map[ghost.lasty][ghost.lastx] == 47){
        x0 = ghost.lastx * TILE_WIDTH + HORIZONTAL_OFFSET;
        y0 = ghost.lasty * TILE_HEIGHT;
        x1 = x0 + TILE_WIDTH - 1;
        y1 = y0 + TILE_HEIGHT - 1;

        tile_map[ghost.lasty][ghost.lastx] == 46 ? tft_write_tile(tile_46, x0, y0, x1, y1) :
                                                   tft_write_tile(tile_47, x0, y0, x1, y1);

    }
}

void redraw_black_in_house(GhostState ghost){
    uint16_t fill_color = BLACK;
    
    uint16_t x0;
    uint16_t y0;
    uint16_t x1;
    uint16_t y1;

    if(ghost.color == COLOR_RED && (ghost.x == OUT_START_LEFT_X && ghost.y == OUT_START_LEFT_Y)){
        // Redraw black inside the left house spot
        x0 = HOUSE_START_LEFT_X * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
        x1 = (x0 + (TILE_WIDTH * 2) - 1);
        y0 = HOUSE_START_LEFT_Y * TILE_HEIGHT - (TILE_HEIGHT / 2);
        y1 = y0 + (2 * TILE_HEIGHT - 1);
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }
    else if(ghost.color == COLOR_PINK && (ghost.x == OUT_START_RIGHT_X && ghost.y == OUT_START_RIGHT_Y)){
        // Redraw black inside the right house spot
        x0 = HOUSE_START_RIGHT_X * TILE_WIDTH + HORIZONTAL_OFFSET - (TILE_WIDTH / 2);
        x1 = (x0 + (TILE_WIDTH * 2) - 1);
        y0 = HOUSE_START_RIGHT_Y * TILE_HEIGHT - (TILE_HEIGHT / 2);
        y1 = y0 + (2 * TILE_HEIGHT - 1);
        tft_fill_region(x0, y0, x1, y1, fill_color);
    }
}

bool check_collision(PacmanState* pacman, GhostState* redghost, GhostState* pinkghost) {
    if (pacman->mode != NORMAL) return false;

    /* Collision detection logic */
    bool hit_ghost = false;
    
    // Check if pacman and red ghost share same tile position
    hit_ghost = ((pacman->x == redghost->x) && (pacman->y == redghost->y)) ||
    // or pacman and red ghost swapped tile positions
    ((pacman->x == redghost->lastx) && (pacman->y == redghost->lasty) && (pacman->lastx == redghost->x) && (pacman->lasty == redghost->y)) ||
    // or pacman and pink ghost share same tile position
    ((pacman->x == pinkghost->x) && (pacman->y == pinkghost->y)) ||
    // or pacman and pink ghost swapped tile positions
    ((pacman->x == pinkghost->lastx) && (pacman->y == pinkghost->lasty) && (pacman->lastx == pinkghost->x) && (pacman->lasty == pinkghost->y));

    return hit_ghost;
}

void draw_end_screen(){    
    uint16_t x0 = 115;
    uint16_t y0 = 13 * TILE_HEIGHT;
    uint16_t x1 = x0 + TILE_WIDTH - 1;
    uint16_t y1 = y0 + TILE_HEIGHT - 1;

    draw_letter(letter_g, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(red_letter_a, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_m, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(red_letter_e, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(tile_45, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_o, x0, y0, x1, y1); // Space
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(letter_v, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(red_letter_e, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(red_letter_r, x0, y0, x1, y1);
    x0 += 8;
    x1 = x0 + TILE_WIDTH - 1;
    draw_letter(red_letter_exclam, x0, y0, x1, y1);
}

void init_chomper_timer(){
    irq_set_exclusive_handler(TIMER0_IRQ_2, chomper_isr);
    timer0_hw->inte |= (1u << 2);
    irq_set_enabled(TIMER0_IRQ_2, true);
    
}

void chomper_isr(){
    // Acknowldege interrupt
    timer0_hw->intr |= (1u << 2);

    // Set his mode back to normal
    pacman.mode = NORMAL;
}

void update_scoreboard(PacmanState* pacman, ScoreBoard* scoreboard, GhostState redghost, GhostState pinkghost){

    if (tile_map[pacman->y][pacman->x] == 46) { // Pellet
        tile_map[pacman->y][pacman->x] = 45;
        scoreboard->num_pellets -= 1;
        scoreboard->total_food -= 1;
        scoreboard->score += 10;
    }
    else if (tile_map[pacman->y][pacman->x] == 47) { // Powerup
        tile_map[pacman->y][pacman->x] = 45;
        scoreboard->num_powers -= 1;
        scoreboard->total_food -= 1;
        scoreboard->score += 50;
        pacman->mode = CHOMPER;

        // Count to 6 seconds then set pacmans mode back to normal (chomper_isr)
        timer0_hw->alarm[2] = timer0_hw->timerawl + 6000000; 
    }
    
    if (((pacman->x == redghost.x && pacman->y == redghost.y)  || (pacman->x == pinkghost.x && pacman->y == pinkghost.y))  && (pacman->mode == CHOMPER)){
        scoreboard->score += 200;
    }
}

void init_ghostunlock_timer() {
    irq_set_exclusive_handler(TIMER1_IRQ_2, ghostunlock_isr);
    timer1_hw->inte |= (1u << 2);
    irq_set_enabled(TIMER1_IRQ_2, true);

    // Ghost unlock value decrements every 1 second if it is in the house (repeating interrupt)
    timer1_hw->alarm[2] = timer1_hw->timerawl + 1000000; 
    
}

void ghostunlock_isr(){
    // Acknowldege interrupt
    timer1_hw->intr |= (1u << 2);

    if (game_state == GAMEPLAY) {
        if(redghost.location == IN_HOUSE){
            redghost.unlock_counter = (redghost.unlock_counter + 1) % 6;
            if(redghost.unlock_counter == 5){
                redghost.location = OUT_HOUSE;
                redghost.x = OUT_START_LEFT_X;
                redghost.y = OUT_START_LEFT_Y;
            }
        }
        else{
            redghost.unlock_counter = 0;
        }

        if(pinkghost.location == IN_HOUSE){
            pinkghost.unlock_counter = (pinkghost.unlock_counter + 1) % 6;
            if(pinkghost.unlock_counter == 5){
                pinkghost.location = OUT_HOUSE;
                pinkghost.x = OUT_START_RIGHT_X;
                pinkghost.y = OUT_START_RIGHT_Y;
            }
        }
        else{
            pinkghost.unlock_counter = 0;
        }
    }
    timer1_hw->alarm[2] = timer1_hw->timerawl + 1000000;
}

void update_ghost(GhostState* ghost, PacmanState pacman){
    
    ghost->lastx = ghost->x;
    ghost->lasty = ghost->y;

    if(ghost->location == IN_HOUSE){
        ghost->x = (ghost->color == COLOR_ORANGE || ghost->color == COLOR_RED) ? HOUSE_START_LEFT_X : HOUSE_START_RIGHT_X;
        ghost->y = (ghost->color == COLOR_ORANGE || ghost->color == COLOR_RED) ? HOUSE_START_LEFT_Y : HOUSE_START_RIGHT_Y;
    }
    else{
        // If the ghost is eaten, teleport them back inside the house
        if ((pacman.mode == CHOMPER) && (ghost->x == pacman.x) && (ghost->y == pacman.y)){
            ghost->x = (ghost->color == COLOR_RED) ? HOUSE_START_LEFT_X : HOUSE_START_RIGHT_X;
            ghost->y = (ghost->color == COLOR_RED) ? HOUSE_START_LEFT_Y : HOUSE_START_RIGHT_Y;
            ghost->location = IN_HOUSE;
        }
        // Otherwise, ghosts follow ai random path ==> DANNY : I used gemini for this part
        else {

            int dx[] = {0, -1, 0, 1}; // UP, LEFT, DOWN, RIGHT
            int dy[] = {-1, 0, 1, 0};

            // 1. Check if the tile directly in front of us is clear
            int next_x = ghost->x + dx[ghost->direction];
            int next_y = ghost->y + dy[ghost->direction];
    
            bool can_move_forward = false;
            if (next_x >= 0 && next_x < NUM_TILES_X && next_y >= 0 && next_y < NUM_TILES_Y) {
                if (tile_map[next_y][next_x] >= 45) { // 45+ are non-wall tiles
                    can_move_forward = true;
                }
            }

            // 2. If we hit a wall OR we are at an intersection, pick a new direction
            // (We use a simple probability to decide to turn at intersections)
            if (!can_move_forward || (rand() % 10 == 0)) { 
                int attempts = 0;
                int new_dir = rand() % 4;
        
                // Try different directions until we find one that isn't a wall
                while (attempts < 8) {
                    int test_x = ghost->x + dx[new_dir];
                    int test_y = ghost->y + dy[new_dir];
            
                    if (test_x >= 0 && test_x < NUM_TILES_X && test_y >= 0 && test_y < NUM_TILES_Y) {
                        if (tile_map[test_y][test_x] >= 45) {
                         // Avoid 180 turn unless we are totally stuck
                            if (new_dir != (ghost->direction + 2) % 4 || attempts > 4) {
                                ghost->direction = new_dir;
                                break;
                            }
                        }
                    }
                    new_dir = (new_dir + 1) % 4;
                    attempts++;
        }
    }
        
        ghost->x += dx[ghost->direction];
        ghost->y += dy[ghost->direction];

        }
    }

}

void display_flash_text(GameState state) {
    static uint32_t flash_text_timer = 0;
    static bool flash_text = false;

    // Flash the start/end menu text every 500 ms
    if (time_us_32() - flash_text_timer > 500000) {
        if (flash_text) {
            (state == STARTING_MENU) ? draw_start_screen() : draw_end_screen();
        } else {
            tft_fill_region(115, 13 * TILE_HEIGHT, 115 + (12 * TILE_WIDTH) - 1, 13 * TILE_HEIGHT + TILE_HEIGHT - 1, BLACK);
        }
        flash_text = !flash_text;
        flash_text_timer = time_us_32();
    }
}
