#include "pico/stdlib.h"
#include "hardware/spi.h"
#include "hardware/gpio.h"
#include "hardware/dma.h"
#include "display.h"

// =============================================================================
// TILE SPRITES ==> https://www.spriters-resource.com/arcade/pacman/asset/73389/
// =============================================================================

const uint16_t tile_1[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE
};

const uint16_t tile_2[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_3[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE
};

const uint16_t tile_4[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_5[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_6[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE
};

const uint16_t tile_7[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
};

const uint16_t tile_8[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_9[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE
};

const uint16_t tile_10[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_11[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_12[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_13[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_14[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_15[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_16[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_17[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_18[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_19[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK
};

const uint16_t tile_20[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

const uint16_t tile_21[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_22[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_23[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_24[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK
};

const uint16_t tile_25[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_26[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
};

const uint16_t tile_27[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_28[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_29[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_30[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
};

const uint16_t tile_31[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_32[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_33[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_34[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE,
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
};

const uint16_t tile_35[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_36[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
};

const uint16_t tile_37[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_38[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_39[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_40[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK
};

const uint16_t tile_41[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_42[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_43[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
};

const uint16_t tile_44[TILE_WIDTH * TILE_HEIGHT] = {
BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK,
};

// EMPTY TILE ===>
const uint16_t tile_45[TILE_WIDTH * TILE_HEIGHT] = {
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
};

// ==========================================================================
//                              END TILE SPRITES
// ==========================================================================

const uint8_t tile_map[NUM_TILES_Y][NUM_TILES_X] = {
    {2, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 44, 43, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 1,},
    {4, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 26, 25, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 3,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,},
    {45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,}
};



void tft_write_command(uint8_t cmd){
    gpio_put(TFT_DC, 0); // Command mode
    gpio_put(TFT_SPI_CSN, 0);
    spi_write_blocking(spi0, &cmd, 1);
    gpio_put(TFT_SPI_CSN, 1);
}

void tft_write_data(uint8_t data){
    gpio_put(TFT_DC, 1); // Data mode
    gpio_put(TFT_SPI_CSN, 0);
    spi_write_blocking(spi0, &data, 1);
    gpio_put(TFT_SPI_CSN, 1);
}

void tft_set_address_window(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) {
    // Column Address Set
    tft_write_command(0x2A);
    tft_write_data(x0 >> 8);
    tft_write_data(x0 & 0xFF);
    tft_write_data(x1 >> 8);
    tft_write_data(x1 & 0xFF);

    // Row Address Set
    tft_write_command(0x2B);
    tft_write_data(y0 >> 8);
    tft_write_data(y0 & 0xFF);
    tft_write_data(y1 >> 8);
    tft_write_data(y1 & 0xFF);

    // Write to RAM
    tft_write_command(0x2C);
}

void display_init(){
    
    // Initialize Pins and SPI
    gpio_init(TFT_SPI_SCK);
    gpio_init(TFT_SPI_MOSI);

    gpio_set_function(TFT_SPI_SCK, GPIO_FUNC_SPI);
    gpio_set_function(TFT_SPI_MOSI, GPIO_FUNC_SPI);

    gpio_init(TFT_SPI_CSN);
    gpio_init(TFT_DC);
    gpio_init(TFT_RST);

    gpio_set_dir(TFT_SPI_CSN, GPIO_OUT);
    gpio_set_dir(TFT_DC, GPIO_OUT);
    gpio_set_dir(TFT_RST, GPIO_OUT);

    spi_init(spi0, 16000000);

    // Reset Display
    gpio_put(TFT_RST, 0);
    sleep_ms(10);
    gpio_put(TFT_RST, 1);
    sleep_ms(10);

    // Basic Initialization Sequence
    tft_write_command(0x01); // Software Reset
    sleep_ms(100);
    tft_write_command(0x11); // Exit Sleep
    sleep_ms(100);

    // Set Pixel Format to 16-bit (RGB565)
    tft_write_command(0x3A);
    tft_write_data(0x55);
    sleep_ms(100);

    // Using Landscape mode. x goes to 319 and y goes to 239 (320x249)
    tft_write_command(0x36);
    tft_write_data(0x28);

    tft_write_command(0x29); // Display ON
}

void tft_fill_screen(uint16_t color) {
    tft_set_address_window(0, 0, 319, 239);

    uint8_t hi = (uint8_t)(color >> 8);
    uint8_t lo = (uint8_t)(color & 0xFF);

    gpio_put(TFT_DC, 1);
    gpio_put(TFT_SPI_CSN, 0);

    // Loop through every pixel on the screen (240 * 320)
    for (uint32_t i = 0; i < (240 * 320); i++) {
        // Send high byte then low byte <--- ILI9341 IS BIG ENDIAN
        spi_write_blocking(spi0, &hi, 1);
        spi_write_blocking(spi0, &lo, 1);
    }

    gpio_put(TFT_SPI_CSN, 1);
}

void tft_write_tile(const uint16_t* tile, uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) {
    tft_set_address_window(x0, y0, x1, y1);

    gpio_put(TFT_DC, 1);
    gpio_put(TFT_SPI_CSN, 0);

    for(int i = 0; i < TILE_HEIGHT * TILE_WIDTH; i ++){
        uint8_t hi = (uint8_t)(tile[i] >> 8);
        uint8_t lo = (uint8_t)(tile[i] & 0xFF);

        spi_write_blocking(spi0, &hi, 1);
        spi_write_blocking(spi0, &lo, 1);
    }

    gpio_put(TFT_SPI_CSN, 1);
}

void draw_map(){
    int tile_sel = 0;
    const uint16_t* tileptr;

    for(int i = 0; i < NUM_TILES_Y; i ++){
        for(int j = 0; j < NUM_TILES_X; j ++){
            
            uint16_t x0 = j * TILE_WIDTH;
            uint16_t y0 = i * TILE_HEIGHT;
            uint16_t x1 = x0 + TILE_WIDTH - 1;
            uint16_t y1 = y0 + TILE_HEIGHT - 1;

            tile_sel = tile_map[i][j];

            switch(tile_sel){
                case(1):
                    tileptr = tile_1;
                    break;
                case(2):
                    tileptr = tile_2;
                    break;
                case(3):
                    tileptr = tile_3;
                    break;
                case(4):
                    tileptr = tile_4;
                    break;
                case(5):
                    tileptr = tile_5;
                    break;
                case(6):
                    tileptr = tile_6;
                    break;
                case(7):
                    tileptr = tile_7;
                    break;
                case(8):
                    tileptr = tile_8;
                    break;
                case(9):
                    tileptr = tile_9;
                    break;
                case(10):
                    tileptr = tile_10;
                    break;
                case(11):
                    tileptr = tile_11;
                    break;
                case(12):
                    tileptr = tile_12;
                    break;
                case(13):
                    tileptr = tile_13;
                    break;
                case(14):
                    tileptr = tile_14;
                    break;
                case(15):
                    tileptr = tile_15;
                    break;
                case(16):
                    tileptr = tile_16;
                    break;
                case(17):
                    tileptr = tile_17;
                    break;
                case(18):
                    tileptr = tile_18;
                    break;
                case(19):
                    tileptr = tile_19;
                    break;
                case(20):
                    tileptr = tile_20;
                    break;
                case(21):
                    tileptr = tile_21;
                    break;
                case(22):
                    tileptr = tile_22;
                    break;
                case(23):
                    tileptr = tile_23;
                    break;
                case(24):
                    tileptr = tile_24;
                    break;
                case(25):
                    tileptr = tile_25;
                    break;
                case(26):
                    tileptr = tile_26;
                    break;
                case(27):
                    tileptr = tile_27;
                    break;
                case(28):
                    tileptr = tile_28;
                    break;
                case(29):
                    tileptr = tile_29;
                    break;
                case(30):
                    tileptr = tile_30;
                    break;
                case(31):
                    tileptr = tile_31;
                    break;
                case(32):
                    tileptr = tile_32;
                    break;
                case(33):
                    tileptr = tile_33;
                    break;
                case(34):
                    tileptr = tile_34;
                    break;
                case(35):
                    tileptr = tile_35;
                    break;
                case(36):
                    tileptr = tile_36;
                    break;
                case(37):
                    tileptr = tile_37;
                    break;
                case(38):
                    tileptr = tile_38;
                    break;
                case(39):
                    tileptr = tile_39;
                    break;
                case(40):
                    tileptr = tile_40;
                    break;
                case(41):
                    tileptr = tile_41;
                    break;
                case(42):
                    tileptr = tile_42;
                    break;
                case(43):
                    tileptr = tile_43;
                    break;
                case(44):
                    tileptr = tile_44;
                    break;
                case(45):
                    tileptr = tile_45;
                    break;
                default:
                    tileptr = tile_45;
            }

            tft_write_tile(tileptr, x0, y0, x1, y1);
            // sleep_ms(5);
        }
    }
}
